import { Poppins } from "next/font/google";
import "./globals.css";
import Navbar from "@/Components/Navbar";
import "slick-carousel/slick/slick.css";
import "slick-carousel/slick/slick-theme.css";
import Footer from "@/Components/Footer";
import "aos/dist/aos.css";
import AOSInit from "@/config/Aos";
import Script from "next/script";
import { SpeedInsights } from "@vercel/speed-insights/next";

const inter = Poppins({
  subsets: ["latin"],
  weight: ["400", "500", "700", "900"],
});

export const metadata = {
  title: "ARTEVIAN",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <script
          src="https://website-widgets.pages.dev/dist/sienna.min.js"
          defer
        ></script>
      </head>
      <body className={inter.className}>
        <SpeedInsights>
          <Navbar />
          {children}
          <Footer />
          <AOSInit />
          <Script
            id="tawk-to"
            strategy="afterInteractive"
            dangerouslySetInnerHTML={{
              __html: `var Tawk_API=Tawk_API||{}, Tawk_LoadStart=new Date();
(function(){
var s1=document.createElement("script"),s0=document.getElementsByTagName("script")[0];
s1.async=true;
s1.src='https://embed.tawk.to/682cc8d88ec535190f1205f4/1irnf1417';
s1.charset='UTF-8';
s1.setAttribute('crossorigin','*');
s0.parentNode.insertBefore(s1,s0);
})();
`,
            }}
          />
          <Script
            src="https://website-widgets.pages.dev/dist/sienna.min.js"
            strategy="afterInteractive"
            defer
          />
        </SpeedInsights>
      </body>
    </html>
  );
}
