import { Poppins } from "next/font/google";
import "./globals.css";
import Navbar from "@/Components/Navbar";
import "slick-carousel/slick/slick.css";
import "slick-carousel/slick/slick-theme.css";
import Footer from "@/Components/Footer";
import "aos/dist/aos.css";
import AOSInit from "@/config/Aos";
import Script from "next/script";
import ErrorBoundary from "@/Components/ErrorBoundary";

const inter = Poppins({
  subsets: ["latin"],
  weight: ["400", "500", "700", "900"],
  display: "swap",
  preload: true,
  fallback: ["system-ui", "arial"],
});

export const viewport = {
  width: "device-width",
  initialScale: 1,
  maximumScale: 1,
  themeColor: "#ffffff",
};

export const metadata = {
  title: "ARTEVIAN",
  description: "Generated by create next app",
  metadataBase: new URL("https://artevian.com"),
  openGraph: {
    title: "ARTEVIAN",
    description: "Your Digital Partner for Creative Solutions",
    url: "https://artevian.com",
    siteName: "ARTEVIAN",
    images: [
      {
        url: "/og-image.jpg",
        width: 1200,
        height: 630,
        alt: "ARTEVIAN",
      },
    ],
    locale: "en_US",
    type: "website",
  },
  twitter: {
    card: "summary_large_image",
    title: "ARTEVIAN",
    description: "Your Digital Partner for Creative Solutions",
    images: ["/og-image.jpg"],
  },
  manifest: "/manifest.json",
  icons: {
    icon: [
      { url: "/favicon.ico", sizes: "any" },
      { url: "/favicon-32x32.png", sizes: "32x32", type: "image/png" },
      { url: "/favicon-16x16.png", sizes: "16x16", type: "image/png" },
    ],
    apple: [
      { url: "/apple-touch-icon.png", sizes: "180x180", type: "image/png" },
    ],
  },
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <link rel="icon" href="/favicon.ico" sizes="any" />
        <link
          rel="icon"
          type="image/png"
          sizes="32x32"
          href="/favicon-32x32.png"
        />
        <link
          rel="icon"
          type="image/png"
          sizes="16x16"
          href="/favicon-16x16.png"
        />
        <link rel="apple-touch-icon" href="/apple-touch-icon.png" />

        {/* Preload critical assets */}
        <link
          rel="preload"
          href="/assets/bgHero1.png"
          as="image"
          type="image/png"
        />
        <link
          rel="preload"
          href="/assets/logo.webp"
          as="image"
          type="image/webp"
        />
      </head>
      <body className={inter.className}>
        <ErrorBoundary>
          <Navbar />
          {children}
          <Footer />
          <AOSInit />
        </ErrorBoundary>

        {/* Tawk.to Chat */}
        <Script
          id="tawk-to"
          strategy="lazyOnload"
          dangerouslySetInnerHTML={{
            __html: `var Tawk_API=Tawk_API||{}, Tawk_LoadStart=new Date();
(function(){
var s1=document.createElement("script"),s0=document.getElementsByTagName("script")[0];
s1.async=true;
s1.src='https://embed.tawk.to/682cc8d88ec535190f1205f4/1irnf1417';
s1.charset='UTF-8';
s1.setAttribute('crossorigin','*');
s0.parentNode.insertBefore(s1,s0);
})();`,
          }}
        />

        {/* ADA Compliance Widget */}
        <Script
          src="https://website-widgets.pages.dev/dist/sienna.min.js"
          strategy="lazyOnload"
        />
      </body>
    </html>
  );
}
